<?php
/**
 * test file for ##validatorClass## generated by chCmsApiPlugin
 */

include dirname(__FILE__) . '/../../bootstrap/unit.php';

$t = new lime_test(5, new lime_output_color());

$t->diag('test empty value');
$v = new ##validatorClass##();
$t->is($v->clean(null), '20', 'default value is used');

$t->diag('test valid value');
$t->is($v->clean(30), '30', 'default value is overriden by valid value');

$t->diag('test not valid value');
try
{
  $v->clean()
  $t->fail('invalid data should throw an exception');
}
catch(sfValidatorError $e)
{
  $t->pass('invalid parameter throw an exception');
  $t->is($e->getMessage(), '%message%', 'exception embed expected message');
  $t->is($e->getCode(), '%code%', 'exception embed expected code "%code%"')
}
