<?php
/**
 * test file for ##paramValidatorClass## generated by chCmsApiPlugin
 */

include dirname(__FILE__) . '/../../bootstrap/unit.php';

$t = new lime_test(6, new lime_output_color());

$t->diag('check for empty values');
$v = new ##paramValidatorClass##();
$v->bind(array());
$t->ok($v->isValid(), 'giving no parameter make ##paramValidatorClass## valid');
$t->is_deeply($v->getValues(), array(), 'default values are what expected');

$t->diag('check with bad params');
$v = new ##paramValidatorClass##();
$v->bind(array(
    'param' => 'bad value'));
$t->ok(!$v->isValid(), 'giving bad parameters make ##paramValidatorClass## invalid');
$t->is_deeply($v->getErrorParameters(), array(
                  'param' => "error message"), 'errors are ok for invalid paramters "param"');

$t->diag('check with valid params');
$v = new ##paramValidatorClass##();
$v->bind(array(
    'param' => 'good value'));
$t->ok($v->isValid(), 'giving bad parameters make ##paramValidatorClass## valid');
$t->is_deeply($v->getValues(), array(
    'param' => 'good value'), 'default values are what expected');
