<?php
/**
 * test file for ##paramValidatorClass## generated by chCmsApiPlugin
 */

include dirname(__FILE__) . '/../../../../../test/bootstrap/unit.php';

class ##paramValidatorClass##Test extends chCmsParamValidatorUnitTest
{
  public function getClassname()
  {
    return '##paramValidatorClass##';
  }

  public function testEmptyValues()
  {
    $this->expect(1);
    $this->assert_clean_ok($this->getValidator(), array(), array());
  }

  public function testBadParameters()
  {
    $this->expect(1);
    $params = array('param' => 'bad value');
    $this->assert_clean_not_ok($this->getValidator(), $params, 'code', "error message");
  }

  public function testValidParameters()
  {
    $this->expect(1);
    $expected = array();
    $params = array();
    $this->assert_clean_ok($this->getValidator(), $params, $expected);
  }
}
new ##paramValidatorClass##Test();
