<?php
/**
 * test file for chCmsApiValidatorParamNotYetImplemented generated by chCmsApiPlugin
 */

include dirname(__FILE__) . '/../../bootstrap/unit.php';

$t = new lime_test(3, new lime_output_color());

$t->diag('test empty value');
$v = new chCmsApiValidatorParamNotYetImplemented();
$t->is($v->clean(null), null, 'default value is used');

$t->diag('test not valid value');
try
{
  $v->clean("*");
  $t->fail('any data should throw an exception');
}
catch (sfValidatorError $e)
{
  $t->pass('invalid parameter throw an exception');
  $t->is($e->getMessage(), 'this parameter is not implmented yet.', 'exception embed expected message');
}
