<?php
/**
 * test file for chCmsParamCoordinatesValidator generated by chCmsApiPlugin
 */

include dirname(__FILE__) . '/../../bootstrap/unit.php';

$t = new lime_test(12, new lime_output_color());

$t->diag('test empty value');
$v = new chCmsParamCoordinatesValidator(array('required' => false));
$t->is($v->clean(null), null, 'default value is null');

$t->diag('test required');
$v = new chCmsParamCoordinatesValidator(array('required' => true));
try
{
  $v->clean(null);
  $t->fail('required does not throw exception if no value is provided');
}
catch (sfValidatorError $e)
{
  $t->pass('required option requires a value');
}

$t->diag('test valid value');
$t->is_deeply($v->clean(array(
    'lat' => 19.134567, 'long' => -12.23456)), array(
    'lat' => 19.134567, 'long' => -12.23456), 'default value is overriden by valid value');

$t->diag('test not valid value');
try
{
  $v->clean("test");
  $t->fail('invalid data should throw an exception');
}
catch (sfValidatorError $e)
{
  $t->pass('invalid parameter throw an exception');
  $t->is($e->getMessage(), 'please provide lat/long array', 'exception embed expected message');
  $t->is($e->getCode(), 'bad_format', 'exception embed expected code "bad_format"');
}

try
{
  $v->clean(array('lat' => -180.0000234, 'long' => 80.000023));
  $t->fail('invalid data should throw an exception');
}
catch (sfValidatorError $e)
{
  $t->pass('invalid parameter throw an exception');
  $t->is($e->getMessage(), 'Invalid.', 'exception embed expected message');
  $t->is($e->getCode(), 'invalid', 'exception embed expected code "invalid"');
}

try
{
  $v->clean(array('lat' => -780.0000234, 'long' => -280.000023));
  $t->fail('invalid data should throw an exception');
}
catch (sfValidatorError $e)
{
  $t->pass('invalid parameter throw an exception');
  $t->is($e->getMessage(), 'Invalid.', 'exception embed expected message');
  $t->is($e->getCode(), 'invalid', 'exception embed expected code "invalid"');
}
