<?php
/**
 * test file for chCmsValidatorApiBase generated by chCmsApiPlugin
 */

include dirname(__FILE__) . '/../../bootstrap/unit.php';

$t = new lime_test(4, new lime_output_color());

class TestchCmsValidatorApiBase extends chCmsValidatorApiBase
{
  function doClean($v) {return $v;}
  function throwApiError($code, $message = 'empty message') {return parent::throwApiError($code, $message);}
}

$t->diag('test empty value');
$v = new TestchCmsValidatorApiBase();

$t->diag('test throwApiError');
try
{
  $v->throwApiError('INVALID_PARAMETER', 'my message');
}
catch (chCmsApiErrorException $e)
{
  $t->pass('invalid parameter throw an exception');
  $t->is($e->getMessage(), 'my message', 'exception embed expected message');
  $t->is($e->getApiCode(), 'INVALID_PARAMETER', 'exception embed expected code "INVALID_PARAMETER"');
  $t->like($e->getCode(), "#^4#", 'thrown error is a "4xx"');
}
catch (Exception $e)
{
  $t->fail('exception thrown by "throwApiError" should be a "chCmsApiErrorException"');
}
