<?php
/**
 * test file for chCmsParamLocationValidator generated by chCmsApiPlugin
 */

include dirname(__FILE__) . '/../../../../../test/bootstrap/unit.php';

$t = new lime_test(10, new lime_output_color());

$geocoder = new \Geocoder\Geocoder();
$provider = new GeocoderDummyProvider();
$geocoder->registerProvider($provider);

$provider->data = array(
  '12 rue des gras, 63000 Clermont ferrand' => array(
    'latitude'  => 45.7787732,
    'longitude' => 3.0845936,
  )
);

$t->diag('test empty value');
$v = new chCmsParamLocationValidator(array('required' => false, 'geocoder' => $geocoder));
$t->is($v->clean(null), null, 'required false is ok');

$t->diag('test required');
$v = new chCmsParamLocationValidator(array('required' => true, 'geocoder' => $geocoder));
try
{
  $v->clean(null);
  $t->fail('required does not throw exception if no value is provided');
}
catch (sfValidatorError $e)
{
  $t->pass('required option requires a value');
}

$t->diag('test valid value');
$r = $v->clean("12 rue des gras, 63000 Clermont ferrand");
$t->is($r->getLatitude(), 45.7787732, 'The latitude is correct');
$t->is($r->getLongitude(), 3.0845936, 'The longitude is correct');

$t->diag('test not valid value');
try
{
  $r = $v->clean("kkjsdqmlkj");
  $t->fail('invalid data should throw an exception');
}
catch (sfValidatorError $e)
{
  $t->pass('invalid parameter throw an exception');
  $t->is($e->getMessage(), 'Invalid data "%message%".', 'exception embed expected message');
  $t->is($e->getCode(), 'invalid', 'exception embed expected code "invalid"');
}

try
{
  $v->clean("un");
  $t->fail('invalid data should throw an exception');
}
catch (sfValidatorError $e)
{
  $t->pass('invalid parameter throw an exception');
  $t->is($e->getMessage(), '"%value%" is too short (%min_length% characters min).', 'exception embed expected message');
  $t->is($e->getCode(), 'min_length', 'exception embed expected code "min_length"');
}

