<?php
/**
 * test file for chCmsParamDateValidator generated by chCmsApiPlugin
 */

include dirname(__FILE__) . '/../../bootstrap/unit.php';

$t = new lime_test(10, new lime_output_color());

$t->diag('test empty value');
$v = new chCmsParamDateValidator();
$t->is($v->clean(null), null, 'default value is used');

$v = new chCmsParamDateValidator(array('default' => 'now'));
$t->isa_ok($v->clean(null), 'DateTime', 'default value can be "now"');


$v = new chCmsParamDateValidator(array('default' => '2005-08-15T15:52:01+0000'));
$t->is($v->clean(null)->format(DateTime::ISO8601), '2005-08-15T15:52:01+0000', 'default value can be in default format');

$t->diag('test valid value');
$v = new chCmsParamDateValidator();
$t->is($v->clean("2005-08-15T15:52:01+0000")->format(DateTime::ISO8601), '2005-08-15T15:52:01+0000', 'default value is overriden by valid value');

$v = new chCmsParamDateValidator(array('required' => true));
$t->diag('test required');
try
{
  $v->clean(null);
  $t->fail('null data should throw an exception');
}
catch (sfValidatorError $e)
{
  $t->pass('null parameter throw an exception');
  $t->is($e->getMessage(), 'Please provide a date.', 'exception embed expected message');
  $t->is($e->getCode(), 'required', 'exception embed expected code "invalid"');
}

$t->diag('test not valid value');
try
{
  $v->clean("2005-08-15");
  $t->fail('invalid data should throw an exception');
}
catch (sfValidatorError $e)
{
  $t->pass('invalid parameter throw an exception');
  $t->is($e->getMessage(), 'Invalid date "2005-08-15".', 'exception embed expected message');
  $t->is($e->getCode(), 'invalid', 'exception embed expected code "invalid"');
}

