<?php
/**
 * test file for chCmsParamDateIntervalValidator generated by chCmsApiPlugin
 */

include dirname(__FILE__) . '/../../bootstrap/unit.php';

function makeInterval($start, $end)
{
  return sprintf('%s|%s',
    date(DateTime::ISO8601, strtotime($start)),
    date(DateTime::ISO8601, strtotime($end))
  );
}

function makePostValidatorInterval($start, $end)
{
  return array(
    'start_date' => date(DateTime::ISO8601, strtotime($start)),
    'end_date'   => date(DateTime::ISO8601, strtotime($end))
  );
}

$t = new lime_test(23, new lime_output_color());

$t->diag('test empty value');
$v = new chCmsParamDateIntervalValidator(array(
  'required' => false
));
$t->is($v->clean(null), null, 'default value is used');

$t->diag('test valid value');
$t->is(
  $v->clean(makeInterval('now', '+1 hour')),
  array(
    new DateTime('now'),
    new DateTime('now +1 hour')
  ),
  'default value is overriden by valid value'
);

$t->diag('test not valid value');
try
{
  $v->clean("%bad param%");
  $t->fail('invalid data should throw an exception');
}
catch (sfValidatorError $e)
{
  $t->pass('invalid parameter throw an exception');
  $t->is($e->getMessage(), 'Invalid interval "%bad param%".', 'exception embed expected message');
  $t->is($e->getCode(), 'invalid', 'exception embed expected code "invalid"');
}

$v = new chCmsParamDateIntervalValidator(array(
  'min_interval' => '2 hour'
));

$t->diag('test not valid value (interval too small)');
$interval = makeInterval('now', '+1 hour');
try
{
  $v->clean($interval);
  $t->fail('invalid data should throw an exception');
}
catch (sfValidatorError $e)
{
  $t->pass('invalid parameter throw an exception');
  $t->is($e->getMessage(), sprintf('Incorrect interval "%s".', $interval), 'exception embed expected message');
  $t->is($e->getCode(), 'inconsistent', 'exception embed expected code "inconsistent"');
}

$t->diag('test valid value');
$t->is(
  $v->clean(makeInterval('now', '+2 hour')),
  array(
    new DateTime('now'),
    new DateTime('now +2 hour')
  ),
  'a large enough interval is valid'
);


$v = new chCmsParamDateIntervalValidator(array(
  'max_interval'  => '2 hour',
));

$t->diag('test not valid value (interval too small)');
$interval = makeInterval('now', '+3 hour');
try
{
  $v->clean($interval);
  $t->fail('invalid data should throw an exception');
}
catch (sfValidatorError $e)
{
  $t->pass('invalid parameter throw an exception');
  $t->is($e->getMessage(), sprintf('Incorrect interval "%s".', $interval), 'exception embed expected message');
  $t->is($e->getCode(), 'inconsistent', 'exception embed expected code "inconsistent"');
}

$t->diag('test valid value');
$t->is(
  $v->clean(makeInterval('now', '+1 hour')),
  array(
    new DateTime('now'),
    new DateTime('now +1 hour')
  ),
  'a large enough interval is valid'
);

$interval = makeInterval('+1 hour', 'now');
try
{
  $v->clean($interval);
  $t->fail('invalid data should throw an exception');
}
catch (sfValidatorError $e)
{
  $t->pass('invalid parameter throw an exception');
  $t->is($e->getMessage(), sprintf('Incorrect interval "%s".', $interval), 'exception embed expected message');
  $t->is($e->getCode(), 'inconsistent', 'exception embed expected code "inconsistent"');
}

$interval = makeInterval('now -1 day', '+1 hour');
try
{
  $v->clean($interval);
  $t->fail('invalid data should throw an exception');
}
catch (sfValidatorError $e)
{
  $t->pass('invalid parameter throw an exception');
  $t->is($e->getMessage(), sprintf('Incorrect interval "%s".', $interval), 'exception embed expected message');
  $t->is($e->getCode(), 'inconsistent', 'exception embed expected code "inconsistent"');
}

$t->diag('test valid value, using the validator as a post-validator');
$t->is(
  $v->clean(makePostValidatorInterval('now', '+1 hour')),
  array_merge(
    makePostValidatorInterval('now', '+1 hour'), array(
      'interval' => array(
        new DateTime('now'),
        new DateTime('now +1 hour')
      )
    )
  ),
  'a large enough interval is valid'
);

try
{
  $v->clean(array(
    'start_date'  => 'foo',
  ));
  $t->fail('invalid data should throw an exception');
}
catch (sfValidatorError $e)
{
  $t->pass('invalid parameter throw an exception');
  $t->is($e->getMessage(), 'Required.', 'exception embed expected message');
  $t->is($e->getCode(), 'required', 'exception embed expected code "required"');
}